### ISSUE TITLE
Lua linking issues

### ISSUE THREAD

**Issue by cabjr** [EPuncker/orts2#120]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://github.com/EPuncker/orts2/issues/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Clone & Compile TFS 1.4
2. Use this data pack with it
3. Run TFS

### Expected behavior
No errors, action scripts should work and NPCs/quests as well

### Actual behavior
![image](https://user-images.githubusercontent.com/21093115/225300387-5659b468-d609-4427-9577-eb05e7b320d5.png)

![image](https://user-images.githubusercontent.com/21093115/225300152-53d0a2f5-1a92-41ac-83b5-1f1661f663ec.png)

### Environment
This was tested using Ubuntu 20.04 and TFS 1.4 (branch on the official repo)

**Comment by EPuncker** [comment]
this datapack is supposed to be used with tfs master, not 1.4

**Comment by cabjr** [comment]
Oh my bad, I came into this repo from an old link in Otland.net that mentioned about using this with TFS 1.4. Closing this, thank you @EPuncker
