### ISSUE TITLE
Missing Monsters and console erros

### ISSUE THREAD

**Issue by omarcopires** [EPuncker/orts2#26]
With the latest pull request map update (https://github.com/EPuncker/orts2/commit/7cb099a82167f7cf14fe192812fb64382395f438) some non-existent monsters in the pack have been added, they are:
- [x] Ogre Savage
- [x] Clomp
- [x] Ogre Shaman
- [x] Ogre Brute
- [x] Werebear
- [x] Wereboar
- [x] Glooth Brigand
- [x] Glooth Bandit
- [x] Glooth Bomb
- [x] High Voltage Elemental
- [x] Glooth Battery
- [x] Control Tower
- [x] Seacrest Serpent

Console Erros:
```[Warning - Spawns::startup] Couldn't spawn monster "Glooth Battery" on position: ( 33536 / 32053 / 013 ).
[Warning - Spawns::startup] Couldn't spawn monster "High Voltage Elemental" on position: ( 33535 / 32054 / 013 ).
[Warning - Spawns::startup] Couldn't spawn monster "Clomp" on position: ( 33646 / 31652 / 007 ).
[Warning - Spawns::startup] Couldn't spawn monster "Clomp" on position: ( 33511 / 31607 / 007 ).

**Comment by EPuncker** [comment]
closed with #27
