### ISSUE TITLE
Minor stuff - Yala drag corpses, eggs, very noble-looking watch, thais hole

### ISSUE THREAD

**Issue by peloverde** [EPuncker/orts2#30]
Hey guys! :) found some new stuff
-Dragon: While looking at a dragon corpse you get the wrong message, those that spwan dead and decayed on the map(yalahar elf), ingame id 4027, 18:51 You see a slain **ghoul** (Vol:24).

-Egg: not usable as food, ingame id 3606, "You cannot use this object."

-Very noble-looking watch: ingame id 6091, should show time and then decay after a while. "You cannot use this object." 
"When you use it, you'll receive the following message informing the current time: The time is hh:mm.
After 24 hours, it will break and become a Broken Very Noble-Looking Watch."

-Thais hole: Item ID: 468 Position: 32359, 32282, 7. It opens with shovel but you can't go down. I'm not really sure about this one, I can't go on global to see if this one is like that and i don't really remember where it leads either, sry.

**Comment by EPuncker** [comment]
egg id is 2328 👅

**Comment by peloverde** [comment]
weird ill get rme and check again.

**Comment by peloverde** [comment]
egg id 2695
dragon id 2846 should be 2847 i guess

**Comment by peloverde** [comment]
watch: fixed it, needed an action.
actions.xml line 480 added
	<action itemid="6092" script="other/watch.lua" />

**Comment by EPuncker** [comment]
thanks
