### ISSUE TITLE
Stackable gems

### ISSUE THREAD

**Issue by torresmon** [EPuncker/orts2#37]
### Explanation of what you want to do that is currently impossible
 i know this is a new-ish addition to global but, if possible, it would be really cool to be able to stack those damn gems

### Desired functionality
stackable violet gem id:2153, yellow gem id:2154, green gem id:2155, red gem id:2156 and blue gem id:2158

### Available workarounds
spending half an hour organizing backpacks :(

**Comment by EPuncker** [comment]
for them to be stackable server side (.otb), they need to be stackable client side as well (.dat), this will require us to provide the client files as well since people using original client will get debug

**Comment by torresmon** [comment]
oh well. at lest i learned something new
