### ISSUE TITLE
Missing monsters - startup warnings thrown

### ISSUE THREAD

**Issue by silic0nalph4** [EPuncker/orts2#49]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://github.com/EPuncker/orts2/issues/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Start latest TFS+ORTS2
2. Watch the startup logs

### Expected behaviour
Log warnings about missing monsters should not be thrown.

### Actual behaviour
Warnings are thrown stating that the game cannot spawn the following monsters:

```
server_1      | [Warning - Spawn::addMonster] Can not find Cult Believer
server_1      | [Warning - Spawn::addMonster] Can not find Cult Enforcer
server_1      | [Warning - Spawn::addMonster] Can not find Cult Scholar
server_1      | [Warning - Spawn::addMonster] Can not find Ghost Wolf
server_1      | [Warning - Spawn::addMonster] Can not find Gloom Wolf
server_1      | [Warning - Spawn::addMonster] Can not find Renegade Knight
server_1      | [Warning - Spawn::addMonster] Can not find Vicious Squire
server_1      | [Warning - Spawn::addMonster] Can not find Vile Grandmaster
server_1      | [Warning - Spawn::addMonster] Can not find Werebadger
```

These monsters are referred to in `data/world/map-spawn.xml` but no corresponding files exist in `data/monster/monsters`.

### Environment

I don't think this issue is environment specific.

I've reproduced this with TFS v1.4 + ORTS2 2c00e4ab9 and also TFS `master` + ORTS2 `main`.

The exact environment I'm running is version controlled here: https://github.com/silic0nalph4/nova-secura-10

### Reproduction environment

I'd be very surprised if you couldn't reproduce this as it seems to just be a case of missing files, but will happily provide more details if it's more complicated than that.

Here's the full server startup log for additional details: [2021-09-30_tfs_orts2_startup.log](https://github.com/EPuncker/orts2/files/7255568/2021-09-30_tfs_orts2_startup.log)

**Comment by EPuncker** [comment]
yes this is a known issue, we just hadn't time to include all the missing monsters yet

**Comment by silic0nalph4** [comment]
Ah, that's fair. Apologies - I couldn't see it on the to-do list tickets so thought I should raise it.

While we're on this thread, I'm seeing a couple of weird issues I'm not quite sure how to explain in a GH issue yet:
- Monsters aren't dropping any loot
- When I use the "look" function of the client (OTClient 10.98) there's no response, whether I'm looking at a rat, a door, the floor etc.

I verified both of these last night by reverting my setup to the default TFS `forgotten` datapack and confirmed that I'm only seeing them in ORTS2. Are these known issues? (Let me know if you want me to just file new GH issues for them straight away)

I'm happy to attempt a fix, but I'm not familiar enough with TFS yet. Is there anywhere in the code you could point me towards so I could attempt to find the root cause?

And perhaps more importantly, is there any way I can buy you a beer or a coffee to say thank you for an exciting map pack? :)

**Comment by EPuncker** [comment]
I'll have a look at these issues today, most likely to be eventcallback issues (at data/script/eventcallbacks), as for a thank you I'm accepting tibia coins to **Animal Activist** character

**Comment by EPuncker** [comment]
see if https://github.com/EPuncker/orts2/commit/f2b3842975713bb6e099d0b7ec472dcb881bfbb5 fix it for you 😋

**Comment by silic0nalph4** [comment]
That worked! 🎉

I can see! `Look` works again!
![image](https://user-images.githubusercontent.com/89796310/135522873-75d14a73-2d52-4952-9722-6696fc492048.png)

Loot works! I can finally leave the first dungeon 😂
![image](https://user-images.githubusercontent.com/89796310/135523038-c6f8138c-eccc-4342-ac5d-f0ede2d8e606.png)

Doors... aren't working. I've dug some digging and my code from last night blatantly didn't work. Sorry! New PR incoming, just testing the last bits.
![image](https://user-images.githubusercontent.com/89796310/135523556-dec675a5-6c7d-4fab-9d70-5b7d414e93f8.png)
