### ISSUE TITLE
Can we run it on TFS 1.4?

### ISSUE THREAD

**Issue by the-overdriven** [EPuncker/orts2#54]
Hi, sorry for asking here but this [thread ](https://otland.net/threads/10-98-orts-real-map-data-pack-for-latest-tfs.274769/) seems to bo closed. Can I run this datapack on TFS 1.4?

I've tried by simply replacing the data folder, but when I run tfs locally on Windows it just exits at "Loading map". No idea why, TFS didn't generate any logs.

**Comment by EPuncker** [comment]
its works with tfs of commit 3333 and bellow, currently tfs is at commit 3510

sorry I don't have any intention of updating this project

**Comment by omarcopires** [comment]
Could you please check with commit #56
