### ISSUE TITLE
Outlaw Camp map stuff

### ISSUE THREAD

**Issue by torresmon** [EPuncker/orts2#59]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://github.com/EPuncker/orts2/issues/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Using doors
2. Doing outlaw camp quest

### Expected behaviour

1. Some doors in outlaw camp had issues with the new door system because of their ids
2. Two doors wouldn't work with their keys: AIDs: 3301 and 3302
3.  Some map parts just doesn't look right

### Actual behaviour

1. Doors transforming into stairs, walls, etc.
2. Doors that should be locked by default are open and the key doesn't work
3. Map problems enabling shortcuts or other weird stuff

### Environment

10.98 + TFS1.4 + win64 + main and 12.86 + LatestTFS + win64 + upstream

1. Doors transforming into stairs, walls, etc:

- 12692:
![12692](https://user-images.githubusercontent.com/70948057/163713949-c49e816a-935d-4337-bf2d-224f6e3a4f3b.png)

- 12695:
![12695](https://user-images.githubusercontent.com/70948057/163713903-a2820083-049f-41a8-bab4-d0d7055b7c38.png)

- 12703:
![12703](https://user-images.githubusercontent.com/70948057/163713929-aa3db513-cc91-4e13-a25f-6ca66771a4c7.png)

(those are the ones i managed to find, i'll keep looking for more)

2. Doors that should be locked by default are open and the key doesn't work:

- aid 3301 and 3302:
![bright sword aid 3301 3302](https://user-images.githubusercontent.com/70948057/163714018-29f74f99-9f63-495e-8863-026541ff1f29.png)

3. Map problems enabling shortcuts or other weird stuff:

- Pretty sure this should be closed kinda like on the right side, otherwise it becomes a shortcut:
![should be closed](https://user-images.githubusercontent.com/70948057/163714066-2b3566c0-564b-4830-a73e-93c46e7309e8.png)

- Pretty sure there should be a trapdoor like on the right side:
![missing trapdoor](https://user-images.githubusercontent.com/70948057/163714168-60c23a7e-d086-4741-9f0c-3006b610d263.png)

- This roof doesn't behave like it should i think:
![roof](https://user-images.githubusercontent.com/70948057/163714858-c4e4ae76-e075-4a60-ab9f-ce385ceaa06a.png)

**Comment by omarcopires** [comment]
do you have discord?

**Comment by torresmon** [comment]
![serpentine lever 29916 to 30149](https://user-images.githubusercontent.com/70948057/164150147-32c4c2f5-3a5c-46fa-a11b-ecc8e83cd6eb.png)
serpentine lever 29916 - 30149

**Comment by torresmon** [comment]
eu fiz algo que não devia? o.o

**Comment by torresmon** [comment]
torresmon#0369
