### ISSUE TITLE
onUsePick tile returning nil

### ISSUE THREAD

**Issue by peloverde** [EPuncker/orts2#6]
got this one while trying to use a pick on different tiles near venore

Lua Script Error: [Action Interface]
data/actions/scripts/tools/pick.lua:onUse
data/actions/lib/actions.lua:283: attempt to index a nil value (global 'tile')
stack traceback:
        [C]: in metamethod 'index'
        data/actions/lib/actions.lua:283: in function 'onUsePick'
        (...tail calls...)

**Comment by peloverde** [comment]
another nil, this time on PlayerStorageKeys.
got this one while trying to use: plague mask - id: 12786

Lua Script Error: [Scripts Interface]
C:\Users\o7\Documents\TIBIA\SERVAO\SERVER\forgottenserver-master\data\scripts\actions\others\afflicted_outfit.lua:callback
...-master\data\scripts\actions\others\afflicted_outfit.lua:8: attempt to index a nil value (global 'PlayerStorageKeys')
stack traceback:
        [C]: in metamethod 'index'
        ...-master\data\scripts\actions\others\afflicted_outfit.lua:8: in function <...-master\data\scripts\actions\others\afflicted_outfit.lua:3>

**Comment by EPuncker** [comment]
eu atualizei eles hoje, dá uma olhada:
https://github.com/EPuncker/orts2/blob/main/data/actions/lib/actions.lua
https://github.com/EPuncker/orts2/blob/main/data/scripts/actions/others/afflicted_outfit.lua

**Comment by peloverde** [comment]
blz vou atualizar

**Comment by peloverde** [comment]
pick persistiu, plague mask e plague bell: "You cannot use this object" (droparam pré update)

Lua Script Error: [Action Interface]
data/actions/scripts/tools/pick.lua:onUse
data/actions/lib/actions.lua:283: attempt to index a nil value (global 'tile')
stack traceback:
        [C]: in metamethod 'index'
        data/actions/lib/actions.lua:283: in function 'onUsePick'
        (...tail calls...)

**Comment by peloverde** [comment]
funcionou depois que peguei o afflicted... eu devia ter conferido isso antes. sry

**Comment by EPuncker** [comment]
fixed on https://github.com/EPuncker/orts2/commit/30a862c063d57e10d81afdaf753b180fcb565436
