### ISSUE TITLE
mechanical fishing rod

### ISSUE THREAD

**Issue by peloverde** [EPuncker/orts2#7]
to "fix" mechanical fishing rod
added to data/actions/actions.xml on line 362
`	<action itemid="10223" script="tools/fishing.lua" allowfaruse="1" />`

i have a separated script for it to be able to fish mechanical fish with nails too but it won't work as intended due to yalahar sewers having normal water tiles instead of the green ones. could edit it for swamp id tiles or something but idk it doesn't rlly matter

**Comment by EPuncker** [comment]
I added one here that I quickly made, but need to be tested so I can close this issue if it works:
https://github.com/EPuncker/orts2/commit/07637e60c571605d3341c2632bb3c93f647c3304#diff-fb15076b7c44ce7eedc18feb359a69b6b3ce77dadf705a3e276b3b59246204d6

**Comment by peloverde** [comment]
aight ill try it out. if you want to compare with the one that i had here it is:

`local waterIds = {493, 4608, 4609, 4610, 4611, 4612, 4613, 4614, 4615, 4616, 4617, 4618, 4619, 4620, 4621, 4622, 4623, 4624, 4625, 7236, 10499, 15401, 15402}
local lootTrash = {2234, 2238, 2376, 2509, 2667}
local lootCommon = {2152, 2167, 2168, 2669, 7588, 7589}
local lootRare = {2143, 2146, 2149, 7158, 7159}
local lootVeryRare = {7632, 7633, 10220}
local useWorms = true

function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if not table.contains(waterIds, target.itemid) then
		return false
	end

	local targetId = target.itemid
	if targetId == 10499 then
		local owner = target:getAttribute(ITEM_ATTRIBUTE_CORPSEOWNER)
		if owner ~= 0 and owner ~= player.uid then
			player:sendTextMessage(MESSAGE_STATUS_SMALL, "You are not the owner.")
			return true
		end

		toPosition:sendMagicEffect(CONST_ME_WATERSPLASH)
		target:remove()

		local rareChance = math.random(100)
		if rareChance == 1 then
			player:addItem(lootVeryRare[math.random(#lootVeryRare)], 1)
		elseif rareChance <= 3 then
			player:addItem(lootRare[math.random(#lootRare)], 1)
		elseif rareChance <= 10 then
			player:addItem(lootCommon[math.random(#lootCommon)], 1)
		else
			player:addItem(lootTrash[math.random(#lootTrash)], 1)
		end
		return true
	end

	if targetId ~= 7236 then
		toPosition:sendMagicEffect(CONST_ME_LOSEENERGY)
	end

	if targetId == 493 or targetId == 15402 then
		return true
	end

	player:addSkillTries(SKILL_FISHING, 1)
	if math.random(100) <= math.min(math.max(10 + (player:getEffectiveSkillLevel(SKILL_FISHING) - 10) * 0.597, 10), 50) then
		if useWorms and not player:removeItem("nail", 1) then
			return true
		end

		if targetId == 15401 then
			target:transform(targetId + 1)
			target:decay()

			if math.random(100) >= 97 then
				player:addItem(15405, 1)
				return true
			end
		elseif targetId == 7236 then
			target:transform(targetId + 1)
			target:decay()

			local rareChance = math.random(100)
			if rareChance == 1 then
				player:addItem(7158, 1)
				return true
			elseif rareChance <= 4 then
				player:addItem(2669, 1)
				return true
			elseif rareChance <= 10 then
				player:addItem(7159, 1)
				return true
			end
		end
		player:addItem("mechanical fish", 1)
	end
	return true
end`

**Comment by peloverde** [comment]
it just say "cannot use this object" not sure why or if i'm doing something wrong here
the one above did work tho

**Comment by EPuncker** [comment]
> it just say "cannot use this object" not sure why or if i'm doing something wrong here
> the one above did work tho

[working 100% now](https://github.com/EPuncker/orts2/blob/main/data/scripts/actions/tools/mechanical_fishing.lua) (note that it only work on yalahar sewers, not anywhere else
