### ISSUE TITLE
Lorek

### ISSUE THREAD

**Issue by peloverde** [EPuncker/orts2#8]
not sure if i'm missing a quest or something but i got this from Lorek in port hope when asking for passage to "mountain", "banuta" and "chor" ("west" and "center" are working without console  errors):

Lua Script Error: [Npc interface]
data/npc/scripts/Lorek.lua:onCreatureSay
data/npc/scripts/Lorek.lua:12: attempt to index a nil value (local 'player')
stack traceback:
        [C]: in metamethod 'index'
        data/npc/scripts/Lorek.lua:12: in field 'condition'
        data/npc/lib/npcsystem/keywordhandler.lua:61: in method 'checkMessage'
        data/npc/lib/npcsystem/keywordhandler.lua:168: in method 'processNodeMessage'
        data/npc/lib/npcsystem/keywordhandler.lua:147: in method 'processMessage'
        data/npc/lib/npcsystem/npchandler.lua:427: in method 'onCreatureSay'
        data/npc/scripts/Lorek.lua:7: in function <data/npc/scripts/Lorek.lua:7>

**Comment by EPuncker** [comment]
see if this fix the issue
https://github.com/EPuncker/orts2/commit/7adae29b3d15e3071e62169ca8450c846da3b07d

**Comment by peloverde** [comment]
no luck. lorek hates me now, won't even say hi back:

Lua Script Error: [Npc interface]
data/npc/scripts/Lorek.lua:onCreatureSay
data/npc/lib/npcsystem/keywordhandler.lua:64: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
        [C]: in ?
        [C]: in function 'string.find'
        data/npc/lib/npcsystem/keywordhandler.lua:64: in method 'checkMessage'
        data/npc/lib/npcsystem/keywordhandler.lua:182: in method 'processNodeMessage'
        data/npc/lib/npcsystem/keywordhandler.lua:154: in method 'processMessage'
        data/npc/lib/npcsystem/npchandler.lua:427: in method 'onCreatureSay'
        data/npc/scripts/Lorek.lua:7: in function <data/npc/scripts/Lorek.lua:7>


like hates me, if i eat bananas, drink potions or use spells near him i get those:

whe drinking pot:
(same 11 lines as above plus this at the end)
        [C]: in method 'say'
        data/actions/scripts/other/potions.lua:161: in function <data/actions/scripts/other/potions.lua:127>

when eating food:
(same 11 lines as above plus this at the end)
        [C]: in method 'say'
        data/actions/scripts/other/food.lua:116: in function <data/actions/scripts/other/food.lua:103>

no added text below the 11 lines when using spells.
