### ISSUE TITLE
Blood Beast corpse

### ISSUE THREAD

**Issue by peloverde** [EPuncker/orts2#9]
blood beast(oramond) turns into cyclops corpse on death. loot messages and items seems to be fine.(i mean it doesn't drop glooth stuff but idk if this map have glooth)

13:16 You see a blood beast.
13:16 Loot of a blood beast: a strong health potion, 26 gold coins
13:17 You see a dead cyclops (Vol:30).

**Comment by peloverde** [comment]
similar thing for rustheap golem and metal gargoyle but these two are indeed cyclops cosplaying as other creatures 260hp plus cyclops loot:

13:23 Loot of a rustheap golem: a cyclops toe, a halberd, a wolf tooth chain, a battle shield, a short sword, a plate shield, meat, 23 gold coins
13:23 Loot of a metal gargoyle: a cyclops toe, a halberd, a battle shield, a short sword, a plate shield, meat, 19 gold coins

**Comment by EPuncker** [comment]
yeah we do have support for content up to Oramond, but that is where the ORTS project stopped, we need to add everything from 10.77 and above

**Comment by peloverde** [comment]
alright i like this town. should i look for this stuff to add or keep trying to find bugs?

**Comment by EPuncker** [comment]
bugs, content is quite easy to add later

**Comment by peloverde** [comment]
agreed

**Comment by omarcopires** [comment]
@peloverde I will update the monsters according to the updates made at [The Forgotten Server](https://github.com/otland/forgottenserver) as soon as my Pull Request #16 is added.
I believe that these problems will be solved.

**Comment by EPuncker** [comment]
> @peloverde I will update the monsters according to the updates made at [The Forgotten Server](https://github.com/otland/forgottenserver) as soon as my Pull Request #16 is added.
> I believe that these problems will be solved.

I don't think master tfs has monsters up to oramond as well :(

**Comment by EPuncker** [comment]
fixed on #18
